/**
 * generated by Xtext 2.17.0
 */
package org.xtext.t2.lisp.lisp;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condicao</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.t2.lisp.lisp.Condicao#getCondicao <em>Condicao</em>}</li>
 * </ul>
 *
 * @see org.xtext.t2.lisp.lisp.LispPackage#getCondicao()
 * @model
 * @generated
 */
public interface Condicao extends EObject
{
  /**
   * Returns the value of the '<em><b>Condicao</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.t2.lisp.lisp.Recursion}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condicao</em>' containment reference list.
   * @see org.xtext.t2.lisp.lisp.LispPackage#getCondicao_Condicao()
   * @model containment="true"
   * @generated
   */
  EList<Recursion> getCondicao();

} // Condicao
