/**
 * generated by Xtext 2.17.0
 */
package org.xtext.t2.lisp.lisp;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Decimal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.t2.lisp.lisp.Decimal#getValue <em>Value</em>}</li>
 *   <li>{@link org.xtext.t2.lisp.lisp.Decimal#getValue1 <em>Value1</em>}</li>
 * </ul>
 *
 * @see org.xtext.t2.lisp.lisp.LispPackage#getDecimal()
 * @model
 * @generated
 */
public interface Decimal extends EObject
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see org.xtext.t2.lisp.lisp.LispPackage#getDecimal_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link org.xtext.t2.lisp.lisp.Decimal#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

  /**
   * Returns the value of the '<em><b>Value1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value1</em>' attribute.
   * @see #setValue1(int)
   * @see org.xtext.t2.lisp.lisp.LispPackage#getDecimal_Value1()
   * @model
   * @generated
   */
  int getValue1();

  /**
   * Sets the value of the '{@link org.xtext.t2.lisp.lisp.Decimal#getValue1 <em>Value1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value1</em>' attribute.
   * @see #getValue1()
   * @generated
   */
  void setValue1(int value);

} // Decimal
