/**
 * generated by Xtext 2.17.0
 */
package org.xtext.t2.lisp.lisp;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.t2.lisp.lisp.LispPackage#getDefinition()
 * @model
 * @generated
 */
public interface Definition extends EObject
{
} // Definition
