/**
 * generated by Xtext 2.17.0
 */
package org.xtext.t2.lisp.lisp;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Identifier</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.t2.lisp.lisp.Identifier#getInitial <em>Initial</em>}</li>
 *   <li>{@link org.xtext.t2.lisp.lisp.Identifier#getSubsequent <em>Subsequent</em>}</li>
 * </ul>
 *
 * @see org.xtext.t2.lisp.lisp.LispPackage#getIdentifier()
 * @model
 * @generated
 */
public interface Identifier extends EObject
{
  /**
   * Returns the value of the '<em><b>Initial</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initial</em>' containment reference.
   * @see #setInitial(Initial)
   * @see org.xtext.t2.lisp.lisp.LispPackage#getIdentifier_Initial()
   * @model containment="true"
   * @generated
   */
  Initial getInitial();

  /**
   * Sets the value of the '{@link org.xtext.t2.lisp.lisp.Identifier#getInitial <em>Initial</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Initial</em>' containment reference.
   * @see #getInitial()
   * @generated
   */
  void setInitial(Initial value);

  /**
   * Returns the value of the '<em><b>Subsequent</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subsequent</em>' containment reference.
   * @see #setSubsequent(Subsequent)
   * @see org.xtext.t2.lisp.lisp.LispPackage#getIdentifier_Subsequent()
   * @model containment="true"
   * @generated
   */
  Subsequent getSubsequent();

  /**
   * Sets the value of the '{@link org.xtext.t2.lisp.lisp.Identifier#getSubsequent <em>Subsequent</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Subsequent</em>' containment reference.
   * @see #getSubsequent()
   * @generated
   */
  void setSubsequent(Subsequent value);

} // Identifier
