/**
 * generated by Xtext 2.15.0
 */
package org.xtext.t2.lisp.lisp;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Inteiros</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.t2.lisp.lisp.LispPackage#getInteiros()
 * @model
 * @generated
 */
public interface Inteiros extends Numeros
{
} // Inteiros
