/**
 * generated by Xtext 2.15.0
 */
package org.xtext.t2.lisp.lisp;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.t2.lisp.lisp.List#getNumeros <em>Numeros</em>}</li>
 * </ul>
 *
 * @see org.xtext.t2.lisp.lisp.LispPackage#getList()
 * @model
 * @generated
 */
public interface List extends Definition
{
  /**
   * Returns the value of the '<em><b>Numeros</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.t2.lisp.lisp.Numeros}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Numeros</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Numeros</em>' containment reference list.
   * @see org.xtext.t2.lisp.lisp.LispPackage#getList_Numeros()
   * @model containment="true"
   * @generated
   */
  EList<Numeros> getNumeros();

} // List
