/**
 * generated by Xtext 2.17.0
 */
package org.xtext.t2.lisp.lisp;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Syntax Binding</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.t2.lisp.lisp.SyntaxBinding#getKeyword1 <em>Keyword1</em>}</li>
 *   <li>{@link org.xtext.t2.lisp.lisp.SyntaxBinding#getTransformerExpression <em>Transformer Expression</em>}</li>
 * </ul>
 *
 * @see org.xtext.t2.lisp.lisp.LispPackage#getSyntaxBinding()
 * @model
 * @generated
 */
public interface SyntaxBinding extends EObject
{
  /**
   * Returns the value of the '<em><b>Keyword1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Keyword1</em>' containment reference.
   * @see #setKeyword1(Keyword)
   * @see org.xtext.t2.lisp.lisp.LispPackage#getSyntaxBinding_Keyword1()
   * @model containment="true"
   * @generated
   */
  Keyword getKeyword1();

  /**
   * Sets the value of the '{@link org.xtext.t2.lisp.lisp.SyntaxBinding#getKeyword1 <em>Keyword1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Keyword1</em>' containment reference.
   * @see #getKeyword1()
   * @generated
   */
  void setKeyword1(Keyword value);

  /**
   * Returns the value of the '<em><b>Transformer Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transformer Expression</em>' containment reference.
   * @see #setTransformerExpression(Expression)
   * @see org.xtext.t2.lisp.lisp.LispPackage#getSyntaxBinding_TransformerExpression()
   * @model containment="true"
   * @generated
   */
  Expression getTransformerExpression();

  /**
   * Sets the value of the '{@link org.xtext.t2.lisp.lisp.SyntaxBinding#getTransformerExpression <em>Transformer Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Transformer Expression</em>' containment reference.
   * @see #getTransformerExpression()
   * @generated
   */
  void setTransformerExpression(Expression value);

} // SyntaxBinding
