/**
 * generated by Xtext 2.17.0
 */
package org.xtext.t2.lisp.lisp;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.t2.lisp.lisp.VariableDefinition#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.t2.lisp.lisp.VariableDefinition#getDefine <em>Define</em>}</li>
 * </ul>
 *
 * @see org.xtext.t2.lisp.lisp.LispPackage#getVariableDefinition()
 * @model
 * @generated
 */
public interface VariableDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.t2.lisp.lisp.LispPackage#getVariableDefinition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.t2.lisp.lisp.VariableDefinition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Define</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Define</em>' containment reference.
   * @see #setDefine(Define)
   * @see org.xtext.t2.lisp.lisp.LispPackage#getVariableDefinition_Define()
   * @model containment="true"
   * @generated
   */
  Define getDefine();

  /**
   * Sets the value of the '{@link org.xtext.t2.lisp.lisp.VariableDefinition#getDefine <em>Define</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Define</em>' containment reference.
   * @see #getDefine()
   * @generated
   */
  void setDefine(Define value);

} // VariableDefinition
