/*
 * generated by Xtext 2.15.0
 */
package org.xtext.t2.lisp.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.t2.lisp.ui.internal.LispActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LispExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(LispActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		LispActivator activator = LispActivator.getInstance();
		return activator != null ? activator.getInjector(LispActivator.ORG_XTEXT_T2_LISP_LISP) : null;
	}

}
