/**
 * generated by Xtext 2.15.0
 */
package org.xtext.t2.lisp.ui;

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class LispUiModule /* implements AbstractLispUiModule  */{
}
