/**
 * generated by Xtext 2.15.0
 */
package org.xtext.t2.lisp;

import org.xtext.t2.lisp.LispStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class LispStandaloneSetup extends LispStandaloneSetupGenerated {
  public static void doSetup() {
    new LispStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
