/**
 * generated by Xtext 2.15.0
 */
package org.xtext.t2.lisp.ide;

import com.google.inject.Injector;
import org.xtext.t2.lisp.LispStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class LispIdeSetup extends LispStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from LispRuntimeModule to Module"
      + "\nType mismatch: cannot convert from LispIdeModule to Module");
  }
}
