/*
 * generated by Xtext 2.15.0
 */
package org.xtext.t2.lisp.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.t2.lisp.LispRuntimeModule
import org.xtext.t2.lisp.LispStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class LispIdeSetup extends LispStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new LispRuntimeModule, new LispIdeModule))
	}
	
}
