/*
 * generated by Xtext 2.15.0
 */
package org.xtext.t2.lisp.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class LispGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.t2.lisp.Lisp.Model");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cBeginAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cBeginBeginParserRuleCall_0_0 = (RuleCall)cBeginAssignment_0.eContents().get(0);
		private final Assignment cDefinitionAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cDefinitionDefinitionParserRuleCall_1_0 = (RuleCall)cDefinitionAssignment_1.eContents().get(0);
		
		//Model:
		//	begin=Begin | definition=Definition*;
		@Override public ParserRule getRule() { return rule; }
		
		//begin=Begin | definition=Definition*
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//begin=Begin
		public Assignment getBeginAssignment_0() { return cBeginAssignment_0; }
		
		//Begin
		public RuleCall getBeginBeginParserRuleCall_0_0() { return cBeginBeginParserRuleCall_0_0; }
		
		//definition=Definition*
		public Assignment getDefinitionAssignment_1() { return cDefinitionAssignment_1; }
		
		//Definition
		public RuleCall getDefinitionDefinitionParserRuleCall_1_0() { return cDefinitionDefinitionParserRuleCall_1_0; }
	}
	public class DefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.t2.lisp.Lisp.Definition");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cNumerosParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cExpressionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cDefineParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Definition:
		//	Numeros | Expression | Define;
		@Override public ParserRule getRule() { return rule; }
		
		//Numeros | Expression | Define
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Numeros
		public RuleCall getNumerosParserRuleCall_0() { return cNumerosParserRuleCall_0; }
		
		//Expression
		public RuleCall getExpressionParserRuleCall_1() { return cExpressionParserRuleCall_1; }
		
		//Define
		public RuleCall getDefineParserRuleCall_2() { return cDefineParserRuleCall_2; }
	}
	public class BeginElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.t2.lisp.Lisp.Begin");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBeginKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cDefinitionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDefinitionDefinitionParserRuleCall_2_0 = (RuleCall)cDefinitionAssignment_2.eContents().get(0);
		
		//Begin:
		//	'begin' name=ID definition=Definition*;
		@Override public ParserRule getRule() { return rule; }
		
		//'begin' name=ID definition=Definition*
		public Group getGroup() { return cGroup; }
		
		//'begin'
		public Keyword getBeginKeyword_0() { return cBeginKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//definition=Definition*
		public Assignment getDefinitionAssignment_2() { return cDefinitionAssignment_2; }
		
		//Definition
		public RuleCall getDefinitionDefinitionParserRuleCall_2_0() { return cDefinitionDefinitionParserRuleCall_2_0; }
	}
	public class DefineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.t2.lisp.Lisp.Define");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cDefineKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cNameAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0_1_0 = (RuleCall)cNameAssignment_0_1.eContents().get(0);
		private final Assignment cExpressionAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cExpressionExpressionParserRuleCall_0_2_0 = (RuleCall)cExpressionAssignment_0_2.eContents().get(0);
		private final Assignment cListAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cListListParserRuleCall_1_0 = (RuleCall)cListAssignment_1.eContents().get(0);
		
		//Define:
		//	'define' name=ID expression=Expression | list=List;
		@Override public ParserRule getRule() { return rule; }
		
		//'define' name=ID expression=Expression | list=List
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'define' name=ID expression=Expression
		public Group getGroup_0() { return cGroup_0; }
		
		//'define'
		public Keyword getDefineKeyword_0_0() { return cDefineKeyword_0_0; }
		
		//name=ID
		public Assignment getNameAssignment_0_1() { return cNameAssignment_0_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_1_0() { return cNameIDTerminalRuleCall_0_1_0; }
		
		//expression=Expression
		public Assignment getExpressionAssignment_0_2() { return cExpressionAssignment_0_2; }
		
		//Expression
		public RuleCall getExpressionExpressionParserRuleCall_0_2_0() { return cExpressionExpressionParserRuleCall_0_2_0; }
		
		//list=List
		public Assignment getListAssignment_1() { return cListAssignment_1; }
		
		//List
		public RuleCall getListListParserRuleCall_1_0() { return cListListParserRuleCall_1_0; }
	}
	public class ListElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.t2.lisp.Lisp.List");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cListKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Assignment cNumerosAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNumerosNumerosParserRuleCall_3_0 = (RuleCall)cNumerosAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//List:
		//	'(' 'list' name=ID numeros=Numeros ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'(' 'list' name=ID numeros=Numeros ')'
		public Group getGroup() { return cGroup; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }
		
		//'list'
		public Keyword getListKeyword_1() { return cListKeyword_1; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//numeros=Numeros
		public Assignment getNumerosAssignment_3() { return cNumerosAssignment_3; }
		
		//Numeros
		public RuleCall getNumerosNumerosParserRuleCall_3_0() { return cNumerosNumerosParserRuleCall_3_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}
	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.t2.lisp.Lisp.Expression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cOperacoesAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cOperacoesOperacoesParserRuleCall_0_1_0 = (RuleCall)cOperacoesAssignment_0_1.eContents().get(0);
		private final Assignment cPrimeiroAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cPrimeiroNumerosParserRuleCall_0_2_0 = (RuleCall)cPrimeiroAssignment_0_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		
		//Expression:
		//	'(' operacoes=Operacoes primeiro=Numeros* ')' |
		//	'(' ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'(' operacoes=Operacoes primeiro=Numeros* ')' | '(' ')'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'(' operacoes=Operacoes primeiro=Numeros* ')'
		public Group getGroup_0() { return cGroup_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0_0() { return cLeftParenthesisKeyword_0_0; }
		
		//operacoes=Operacoes
		public Assignment getOperacoesAssignment_0_1() { return cOperacoesAssignment_0_1; }
		
		//Operacoes
		public RuleCall getOperacoesOperacoesParserRuleCall_0_1_0() { return cOperacoesOperacoesParserRuleCall_0_1_0; }
		
		//primeiro=Numeros*
		public Assignment getPrimeiroAssignment_0_2() { return cPrimeiroAssignment_0_2; }
		
		//Numeros
		public RuleCall getPrimeiroNumerosParserRuleCall_0_2_0() { return cPrimeiroNumerosParserRuleCall_0_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_0_3() { return cRightParenthesisKeyword_0_3; }
		
		//'(' ')'
		public Group getGroup_1() { return cGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_1() { return cRightParenthesisKeyword_1_1; }
	}
	public class NumerosElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.t2.lisp.Lisp.Numeros");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cInteirosParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDecimalParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Numeros:
		//	Inteiros | Decimal;
		@Override public ParserRule getRule() { return rule; }
		
		//Inteiros | Decimal
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Inteiros
		public RuleCall getInteirosParserRuleCall_0() { return cInteirosParserRuleCall_0; }
		
		//Decimal
		public RuleCall getDecimalParserRuleCall_1() { return cDecimalParserRuleCall_1; }
	}
	public class OperacoesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.t2.lisp.Lisp.Operacoes");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cValueAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final Keyword cValuePlusSignKeyword_0_0 = (Keyword)cValueAssignment_0.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cAsteriskKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cSolidusKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cSquareKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		
		//Operacoes:
		//	value='+' | '-' | '*' | '/' | 'square';
		@Override public ParserRule getRule() { return rule; }
		
		//value='+' | '-' | '*' | '/' | 'square'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//value='+'
		public Assignment getValueAssignment_0() { return cValueAssignment_0; }
		
		//'+'
		public Keyword getValuePlusSignKeyword_0_0() { return cValuePlusSignKeyword_0_0; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_1() { return cHyphenMinusKeyword_1; }
		
		//'*'
		public Keyword getAsteriskKeyword_2() { return cAsteriskKeyword_2; }
		
		//'/'
		public Keyword getSolidusKeyword_3() { return cSolidusKeyword_3; }
		
		//'square'
		public Keyword getSquareKeyword_4() { return cSquareKeyword_4; }
	}
	public class InteirosElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.t2.lisp.Lisp.Inteiros");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueINTTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//Inteiros:
		//	value=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//value=INT
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_0() { return cValueINTTerminalRuleCall_0; }
	}
	public class DecimalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.t2.lisp.Lisp.Decimal");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cValueAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cValueINTTerminalRuleCall_0_0 = (RuleCall)cValueAssignment_0.eContents().get(0);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueINTTerminalRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		//Decimal:
		//	value=INT '.' value=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//value=INT '.' value=INT
		public Group getGroup() { return cGroup; }
		
		//value=INT
		public Assignment getValueAssignment_0() { return cValueAssignment_0; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_0_0() { return cValueINTTerminalRuleCall_0_0; }
		
		//'.'
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }
		
		//value=INT
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_2_0() { return cValueINTTerminalRuleCall_2_0; }
	}
	
	
	private final ModelElements pModel;
	private final DefinitionElements pDefinition;
	private final BeginElements pBegin;
	private final DefineElements pDefine;
	private final ListElements pList;
	private final ExpressionElements pExpression;
	private final NumerosElements pNumeros;
	private final OperacoesElements pOperacoes;
	private final InteirosElements pInteiros;
	private final DecimalElements pDecimal;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public LispGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pDefinition = new DefinitionElements();
		this.pBegin = new BeginElements();
		this.pDefine = new DefineElements();
		this.pList = new ListElements();
		this.pExpression = new ExpressionElements();
		this.pNumeros = new NumerosElements();
		this.pOperacoes = new OperacoesElements();
		this.pInteiros = new InteirosElements();
		this.pDecimal = new DecimalElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.t2.lisp.Lisp".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	begin=Begin | definition=Definition*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Definition:
	//	Numeros | Expression | Define;
	public DefinitionElements getDefinitionAccess() {
		return pDefinition;
	}
	
	public ParserRule getDefinitionRule() {
		return getDefinitionAccess().getRule();
	}
	
	//Begin:
	//	'begin' name=ID definition=Definition*;
	public BeginElements getBeginAccess() {
		return pBegin;
	}
	
	public ParserRule getBeginRule() {
		return getBeginAccess().getRule();
	}
	
	//Define:
	//	'define' name=ID expression=Expression | list=List;
	public DefineElements getDefineAccess() {
		return pDefine;
	}
	
	public ParserRule getDefineRule() {
		return getDefineAccess().getRule();
	}
	
	//List:
	//	'(' 'list' name=ID numeros=Numeros ')';
	public ListElements getListAccess() {
		return pList;
	}
	
	public ParserRule getListRule() {
		return getListAccess().getRule();
	}
	
	//Expression:
	//	'(' operacoes=Operacoes primeiro=Numeros* ')' |
	//	'(' ')';
	public ExpressionElements getExpressionAccess() {
		return pExpression;
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}
	
	//Numeros:
	//	Inteiros | Decimal;
	public NumerosElements getNumerosAccess() {
		return pNumeros;
	}
	
	public ParserRule getNumerosRule() {
		return getNumerosAccess().getRule();
	}
	
	//Operacoes:
	//	value='+' | '-' | '*' | '/' | 'square';
	public OperacoesElements getOperacoesAccess() {
		return pOperacoes;
	}
	
	public ParserRule getOperacoesRule() {
		return getOperacoesAccess().getRule();
	}
	
	//Inteiros:
	//	value=INT;
	public InteirosElements getInteirosAccess() {
		return pInteiros;
	}
	
	public ParserRule getInteirosRule() {
		return getInteirosAccess().getRule();
	}
	
	//Decimal:
	//	value=INT '.' value=INT;
	public DecimalElements getDecimalAccess() {
		return pDecimal;
	}
	
	public ParserRule getDecimalRule() {
		return getDecimalAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
