/*
 * generated by Xtext 2.15.0
 */
package org.xtext.t2.lisp.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class LispGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.t2.lisp.Lisp.Model");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cDecimalAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cDecimalDecimalParserRuleCall_0_0 = (RuleCall)cDecimalAssignment_0.eContents().get(0);
		private final Assignment cInteirosAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cInteirosInteirosParserRuleCall_1_0 = (RuleCall)cInteirosAssignment_1.eContents().get(0);
		private final Assignment cBeginAssignment_2 = (Assignment)cAlternatives.eContents().get(2);
		private final RuleCall cBeginBeginParserRuleCall_2_0 = (RuleCall)cBeginAssignment_2.eContents().get(0);
		private final Assignment cDefineAssignment_3 = (Assignment)cAlternatives.eContents().get(3);
		private final RuleCall cDefineDefineParserRuleCall_3_0 = (RuleCall)cDefineAssignment_3.eContents().get(0);
		
		//Model:
		//	decimal+=Decimal* | inteiros+=Inteiros* | begin=Begin | define=Define;
		@Override public ParserRule getRule() { return rule; }
		
		//decimal+=Decimal* | inteiros+=Inteiros* | begin=Begin | define=Define
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//decimal+=Decimal*
		public Assignment getDecimalAssignment_0() { return cDecimalAssignment_0; }
		
		//Decimal
		public RuleCall getDecimalDecimalParserRuleCall_0_0() { return cDecimalDecimalParserRuleCall_0_0; }
		
		//inteiros+=Inteiros*
		public Assignment getInteirosAssignment_1() { return cInteirosAssignment_1; }
		
		//Inteiros
		public RuleCall getInteirosInteirosParserRuleCall_1_0() { return cInteirosInteirosParserRuleCall_1_0; }
		
		//begin=Begin
		public Assignment getBeginAssignment_2() { return cBeginAssignment_2; }
		
		//Begin
		public RuleCall getBeginBeginParserRuleCall_2_0() { return cBeginBeginParserRuleCall_2_0; }
		
		//define=Define
		public Assignment getDefineAssignment_3() { return cDefineAssignment_3; }
		
		//Define
		public RuleCall getDefineDefineParserRuleCall_3_0() { return cDefineDefineParserRuleCall_3_0; }
	}
	public class BeginElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.t2.lisp.Lisp.Begin");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBeginKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Begin:
		//	'begin' name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//'begin' name=ID
		public Group getGroup() { return cGroup; }
		
		//'begin'
		public Keyword getBeginKeyword_0() { return cBeginKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	public class DefineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.t2.lisp.Lisp.Define");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDefineKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cExpressionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cExpressionExpressionParserRuleCall_3_0 = (RuleCall)cExpressionAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Define:
		//	'define' name=ID '(' expression=Expression ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'define' name=ID '(' expression=Expression ')'
		public Group getGroup() { return cGroup; }
		
		//'define'
		public Keyword getDefineKeyword_0() { return cDefineKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//expression=Expression
		public Assignment getExpressionAssignment_3() { return cExpressionAssignment_3; }
		
		//Expression
		public RuleCall getExpressionExpressionParserRuleCall_3_0() { return cExpressionExpressionParserRuleCall_3_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}
	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.t2.lisp.Lisp.Expression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cOperacoesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cOperacoesOperacoesParserRuleCall_1_0 = (RuleCall)cOperacoesAssignment_1.eContents().get(0);
		private final Keyword cSpaceKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cInteirosAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cInteirosInteirosParserRuleCall_3_0 = (RuleCall)cInteirosAssignment_3.eContents().get(0);
		private final Keyword cSpaceKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cInteirosAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cInteirosInteirosParserRuleCall_5_0 = (RuleCall)cInteirosAssignment_5.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Expression:
		//	'(' operacoes=Operacoes ' ' inteiros=Inteiros ' ' inteiros=Inteiros ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'(' operacoes=Operacoes ' ' inteiros=Inteiros ' ' inteiros=Inteiros ')'
		public Group getGroup() { return cGroup; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }
		
		//operacoes=Operacoes
		public Assignment getOperacoesAssignment_1() { return cOperacoesAssignment_1; }
		
		//Operacoes
		public RuleCall getOperacoesOperacoesParserRuleCall_1_0() { return cOperacoesOperacoesParserRuleCall_1_0; }
		
		//' '
		public Keyword getSpaceKeyword_2() { return cSpaceKeyword_2; }
		
		//inteiros=Inteiros
		public Assignment getInteirosAssignment_3() { return cInteirosAssignment_3; }
		
		//Inteiros
		public RuleCall getInteirosInteirosParserRuleCall_3_0() { return cInteirosInteirosParserRuleCall_3_0; }
		
		//' '
		public Keyword getSpaceKeyword_4() { return cSpaceKeyword_4; }
		
		//inteiros=Inteiros
		public Assignment getInteirosAssignment_5() { return cInteirosAssignment_5; }
		
		//Inteiros
		public RuleCall getInteirosInteirosParserRuleCall_5_0() { return cInteirosInteirosParserRuleCall_5_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
	}
	public class OperacoesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.t2.lisp.Lisp.Operacoes");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cPlusSignKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cAsteriskKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cSolidusKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cSquareKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		
		//Operacoes:
		//	'+' | '-' | '*' | '/' | 'square';
		@Override public ParserRule getRule() { return rule; }
		
		//'+' | '-' | '*' | '/' | 'square'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'+'
		public Keyword getPlusSignKeyword_0() { return cPlusSignKeyword_0; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_1() { return cHyphenMinusKeyword_1; }
		
		//'*'
		public Keyword getAsteriskKeyword_2() { return cAsteriskKeyword_2; }
		
		//'/'
		public Keyword getSolidusKeyword_3() { return cSolidusKeyword_3; }
		
		//'square'
		public Keyword getSquareKeyword_4() { return cSquareKeyword_4; }
	}
	public class InteirosElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.t2.lisp.Lisp.Inteiros");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueINTTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//Inteiros:
		//	value=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//value=INT
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_0() { return cValueINTTerminalRuleCall_0; }
	}
	public class DecimalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.t2.lisp.Lisp.Decimal");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cValueAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cValueINTTerminalRuleCall_0_0 = (RuleCall)cValueAssignment_0.eContents().get(0);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueINTTerminalRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		//Decimal:
		//	value=INT '.' value=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//value=INT '.' value=INT
		public Group getGroup() { return cGroup; }
		
		//value=INT
		public Assignment getValueAssignment_0() { return cValueAssignment_0; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_0_0() { return cValueINTTerminalRuleCall_0_0; }
		
		//'.'
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }
		
		//value=INT
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_2_0() { return cValueINTTerminalRuleCall_2_0; }
	}
	
	
	private final ModelElements pModel;
	private final BeginElements pBegin;
	private final DefineElements pDefine;
	private final ExpressionElements pExpression;
	private final OperacoesElements pOperacoes;
	private final InteirosElements pInteiros;
	private final DecimalElements pDecimal;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public LispGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pBegin = new BeginElements();
		this.pDefine = new DefineElements();
		this.pExpression = new ExpressionElements();
		this.pOperacoes = new OperacoesElements();
		this.pInteiros = new InteirosElements();
		this.pDecimal = new DecimalElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.t2.lisp.Lisp".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	decimal+=Decimal* | inteiros+=Inteiros* | begin=Begin | define=Define;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Begin:
	//	'begin' name=ID;
	public BeginElements getBeginAccess() {
		return pBegin;
	}
	
	public ParserRule getBeginRule() {
		return getBeginAccess().getRule();
	}
	
	//Define:
	//	'define' name=ID '(' expression=Expression ')';
	public DefineElements getDefineAccess() {
		return pDefine;
	}
	
	public ParserRule getDefineRule() {
		return getDefineAccess().getRule();
	}
	
	//Expression:
	//	'(' operacoes=Operacoes ' ' inteiros=Inteiros ' ' inteiros=Inteiros ')';
	public ExpressionElements getExpressionAccess() {
		return pExpression;
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}
	
	//Operacoes:
	//	'+' | '-' | '*' | '/' | 'square';
	public OperacoesElements getOperacoesAccess() {
		return pOperacoes;
	}
	
	public ParserRule getOperacoesRule() {
		return getOperacoesAccess().getRule();
	}
	
	//Inteiros:
	//	value=INT;
	public InteirosElements getInteirosAccess() {
		return pInteiros;
	}
	
	public ParserRule getInteirosRule() {
		return getInteirosAccess().getRule();
	}
	
	//Decimal:
	//	value=INT '.' value=INT;
	public DecimalElements getDecimalAccess() {
		return pDecimal;
	}
	
	public ParserRule getDecimalRule() {
		return getDecimalAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
