/**
 * generated by Xtext 2.17.0
 */
package org.xtext.t2.lisp.lisp.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.t2.lisp.lisp.Digit;
import org.xtext.t2.lisp.lisp.Initial;
import org.xtext.t2.lisp.lisp.LispPackage;
import org.xtext.t2.lisp.lisp.Subsequent;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Subsequent</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.t2.lisp.lisp.impl.SubsequentImpl#getInitial <em>Initial</em>}</li>
 *   <li>{@link org.xtext.t2.lisp.lisp.impl.SubsequentImpl#getDigit <em>Digit</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SubsequentImpl extends MinimalEObjectImpl.Container implements Subsequent
{
  /**
   * The cached value of the '{@link #getInitial() <em>Initial</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInitial()
   * @generated
   * @ordered
   */
  protected Initial initial;

  /**
   * The cached value of the '{@link #getDigit() <em>Digit</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDigit()
   * @generated
   * @ordered
   */
  protected Digit digit;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SubsequentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LispPackage.Literals.SUBSEQUENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Initial getInitial()
  {
    return initial;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInitial(Initial newInitial, NotificationChain msgs)
  {
    Initial oldInitial = initial;
    initial = newInitial;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LispPackage.SUBSEQUENT__INITIAL, oldInitial, newInitial);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInitial(Initial newInitial)
  {
    if (newInitial != initial)
    {
      NotificationChain msgs = null;
      if (initial != null)
        msgs = ((InternalEObject)initial).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LispPackage.SUBSEQUENT__INITIAL, null, msgs);
      if (newInitial != null)
        msgs = ((InternalEObject)newInitial).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LispPackage.SUBSEQUENT__INITIAL, null, msgs);
      msgs = basicSetInitial(newInitial, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LispPackage.SUBSEQUENT__INITIAL, newInitial, newInitial));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Digit getDigit()
  {
    return digit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDigit(Digit newDigit, NotificationChain msgs)
  {
    Digit oldDigit = digit;
    digit = newDigit;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LispPackage.SUBSEQUENT__DIGIT, oldDigit, newDigit);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDigit(Digit newDigit)
  {
    if (newDigit != digit)
    {
      NotificationChain msgs = null;
      if (digit != null)
        msgs = ((InternalEObject)digit).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LispPackage.SUBSEQUENT__DIGIT, null, msgs);
      if (newDigit != null)
        msgs = ((InternalEObject)newDigit).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LispPackage.SUBSEQUENT__DIGIT, null, msgs);
      msgs = basicSetDigit(newDigit, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LispPackage.SUBSEQUENT__DIGIT, newDigit, newDigit));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LispPackage.SUBSEQUENT__INITIAL:
        return basicSetInitial(null, msgs);
      case LispPackage.SUBSEQUENT__DIGIT:
        return basicSetDigit(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LispPackage.SUBSEQUENT__INITIAL:
        return getInitial();
      case LispPackage.SUBSEQUENT__DIGIT:
        return getDigit();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LispPackage.SUBSEQUENT__INITIAL:
        setInitial((Initial)newValue);
        return;
      case LispPackage.SUBSEQUENT__DIGIT:
        setDigit((Digit)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LispPackage.SUBSEQUENT__INITIAL:
        setInitial((Initial)null);
        return;
      case LispPackage.SUBSEQUENT__DIGIT:
        setDigit((Digit)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LispPackage.SUBSEQUENT__INITIAL:
        return initial != null;
      case LispPackage.SUBSEQUENT__DIGIT:
        return digit != null;
    }
    return super.eIsSet(featureID);
  }

} //SubsequentImpl
