/*
 * generated by Xtext 2.15.0
 */
package org.xtext.t2.lisp.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.t2.lisp.ui.internal.LispActivator;

public class LispUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LispActivator.getInstance().getInjector("org.xtext.t2.lisp.Lisp");
	}

}
